### PR TITLE
Migrate to AndroidX

### PR DESCRIPTION
**Pull request by Holidaybear**
The support library artifacts are being deprecated and all future development is going into AndroidX.

### CODE REVIEW

**Comment by mTwTm** [comment]
Hmmm seems like I need to remove the 27.3 setup in travis ci but I'm currently removed from the organization so I can't do that anymore, you might need to check if you can renew the settings or re-setup one.

**Comment by Holidaybear** [comment]
travis works fine now :)

**Comment by mTwTm** [comment]
Great! As a friendly reminder: You might want to squash the last three commits before merging.

**Review by mTwTm — COMMENTED** [review]
We might want to disable `enableJetifier` once we've migrated all the support library dependencies.

**Comment by Holidaybear** [comment]
oh that's right

**Pull request merged**
