### PR TITLE
Remove .idea

### PR DESCRIPTION
**Pull request by Holidaybear**
as title

### CODE REVIEW

**Comment by mTwTm** [comment]
Per [doc ](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems) from JetBrains, most files under .idea should be shared, do we have a good reason to override this?

**Comment by Holidaybear** [comment]
Oh, I think it's ok if we decide to share IDE information with other developers refer to doc. However, the project's goal is being library component, do we need .idea ?

**Comment by mTwTm** [comment]
My feeling is it's okay since many libs are still developed in Android Studio but I'm also definitely positive with removing these if we are sure about this.

**Comment by Holidaybear** [comment]
OK, let's align with [android-components](https://github.com/mozilla-mobile/android-components)

**Pull request merged**
